#!/bin/sh
# Embeds the app's canonical zone geometry (app/src/shared/zone-defaults.json, the single source of truth) into the
# daemon as Sources/ghostkeysd/Config/ZoneDefaults.generated.swift.
#
#   daemon/scripts/gen-zone-defaults.sh          regenerate (run after editing the JSON, then rebuild)
#   daemon/scripts/gen-zone-defaults.sh --check  exit 1 if the generated file is out of date (for CI / pre-build)
set -eu
here=$(cd "$(dirname "$0")" && pwd)
json="$here/../../app/src/shared/zone-defaults.json"
out="$here/../Sources/ghostkeysd/Config/ZoneDefaults.generated.swift"
[ -f "$json" ] || { echo "missing $json" >&2; exit 1; }
if grep -q '"""##' "$json"; then echo "zone-defaults.json contains the raw-string delimiter" >&2; exit 1; fi
sum=$(shasum -a 256 "$json" | cut -d' ' -f1)

tmp=$(mktemp)
{
  echo "// GENERATED by daemon/scripts/gen-zone-defaults.sh from app/src/shared/zone-defaults.json. Do not edit."
  echo "// Source SHA-256: $sum"
  echo ""
  echo "enum ZoneDefaultsSource {"
  echo "    static let sha256 = \"$sum\""
  echo "    static let json = ##\"\"\""
  cat "$json"
  echo ""
  echo "\"\"\"##"
  echo "}"
} > "$tmp"

if [ "${1:-}" = "--check" ]; then
  if cmp -s "$tmp" "$out"; then rm -f "$tmp"; echo "ZoneDefaults.generated.swift is up to date"; exit 0; fi
  rm -f "$tmp"; echo "ZoneDefaults.generated.swift is stale: run daemon/scripts/gen-zone-defaults.sh" >&2; exit 1
fi
mv "$tmp" "$out"
echo "wrote $out (source $sum)"
