#!/usr/bin/env python3
"""Generates a swift-testing runner package for one test target of the daemon package.

Why: with only the Command Line Tools installed (no Xcode), `swift test` builds swift-testing
suites but silently runs none of them. The workaround is an ordinary executable whose entry point
calls `Testing.__swiftPMEntryPoint()`, which is exactly what `swift test` would have run.

For test target T this writes <out>/<T>/:
  Package.swift              library targets T depends on (transitively) + executable target T
  Sources/<dep>/...          copies of each dependency's sources (target `exclude` entries dropped)
  Sources/<T>/...            copies of T's test files + a generated @main entry point

Usage: make_runner_package.py <package-dir> <dump-package.json> <test-target> <out-dir>
Prints the generated package path. Exits 2 (with a message) if the target cannot be mirrored.
"""
import json
import os
import shutil
import sys

FRAMEWORKS = "/Library/Developer/CommandLineTools/Library/Developer/Frameworks"
ENTRY_FILE = "__GhostkeysTestRunnerMain.swift"
ENTRY_SOURCE = """// Generated by scripts/run-tests.sh. Runs every swift-testing test compiled into this executable.
import Testing

@main
enum GhostkeysTestRunnerMain {
    static func main() async {
        await Testing.__swiftPMEntryPoint() as Never
    }
}
"""


def fail(msg):
    print(msg, file=sys.stderr)
    sys.exit(2)


def swift_str(s):
    return json.dumps(s)  # JSON string escaping is valid Swift string literal escaping for our inputs


def settings_swift(settings, target_name):
    """Translates dump-package settings back into manifest code: (swiftSettings, cSettings, linkerSettings)."""
    out = {"swift": [], "c": [], "cxx": [], "linker": []}
    for s in settings:
        tool, kind = s.get("tool"), s.get("kind", {})
        if s.get("condition"):
            print(f"note: {target_name}: conditional setting dropped: {json.dumps(s)}", file=sys.stderr)
            continue
        if "unsafeFlags" in kind:
            flags = kind["unsafeFlags"]["_0"]
            out[tool].append(".unsafeFlags([" + ", ".join(swift_str(f) for f in flags) + "])")
        elif "define" in kind:
            out[tool].append(f".define({swift_str(kind['define']['_0'])})")
        elif "linkedFramework" in kind:
            out["linker"].append(f".linkedFramework({swift_str(kind['linkedFramework']['_0'])})")
        elif "linkedLibrary" in kind:
            out["linker"].append(f".linkedLibrary({swift_str(kind['linkedLibrary']['_0'])})")
        elif "headerSearchPath" in kind:
            out[tool].append(f".headerSearchPath({swift_str(kind['headerSearchPath']['_0'])})")
        else:
            print(f"note: {target_name}: unsupported setting dropped: {json.dumps(s)}", file=sys.stderr)
    return out


def resources_swift(resources):
    items = []
    for r in resources:
        rule = r.get("rule", {})
        if "copy" in rule:
            items.append(f".copy({swift_str(r['path'])})")
        else:
            items.append(f".process({swift_str(r['path'])})")
    return items


def dep_names(target):
    names = []
    for d in target.get("dependencies", []):
        if "byName" in d:
            names.append(d["byName"][0])
        elif "target" in d:
            names.append(d["target"][0])
        else:
            fail(f"{target['name']}: product dependencies are not supported by the runner generator: {json.dumps(d)}")
    return names


def source_dir(pkg, target):
    if target.get("path"):
        return os.path.join(pkg, target["path"])
    base = "Tests" if target["type"] == "test" else "Sources"
    return os.path.join(pkg, base, target["name"])


def copy_target(src, dst, exclude):
    if os.path.exists(dst):
        shutil.rmtree(dst)
    ignore_abs = {os.path.normpath(os.path.join(src, e)) for e in exclude}

    def ignore(d, names):
        return [n for n in names if os.path.normpath(os.path.join(d, n)) in ignore_abs or n == ".DS_Store"]

    shutil.copytree(src, dst, ignore=ignore)


def main():
    if len(sys.argv) != 5:
        fail(__doc__)
    pkg, dump_path, test_name, out_root = sys.argv[1:]
    with open(dump_path) as f:
        dump = json.load(f)
    targets = {t["name"]: t for t in dump["targets"]}
    test = targets.get(test_name)
    if not test or test["type"] != "test":
        fail(f"{test_name} is not a test target of this package")

    # Transitive library dependencies, dependencies first.
    order, seen = [], set()

    def visit(name):
        if name in seen:
            return
        seen.add(name)
        t = targets.get(name)
        if t is None:
            fail(f"{test_name}: dependency {name} is not a target of this package")
        if t["type"] not in ("regular", "system"):
            fail(f"{test_name}: depends on {name} of type {t['type']}, which the runner cannot link")
        for d in dep_names(t):
            visit(d)
        order.append(name)

    for d in dep_names(test):
        visit(d)

    out = os.path.join(out_root, test_name)
    os.makedirs(os.path.join(out, "Sources"), exist_ok=True)
    # Drop stale target folders from earlier runs.
    for existing in os.listdir(os.path.join(out, "Sources")):
        if existing not in order and existing != test_name:
            shutil.rmtree(os.path.join(out, "Sources", existing))

    decls = []
    for name in order:
        t = targets[name]
        copy_target(source_dir(pkg, t), os.path.join(out, "Sources", name), t.get("exclude", []))
        st = settings_swift(t.get("settings", []), name)
        args = [swift_str(name)]
        deps = dep_names(t)
        if deps:
            args.append("dependencies: [" + ", ".join(swift_str(d) for d in deps) + "]")
        res = resources_swift(t.get("resources", []))
        if res:
            args.append("resources: [" + ", ".join(res) + "]")
        for key, label in (("swift", "swiftSettings"), ("c", "cSettings"), ("cxx", "cxxSettings"), ("linker", "linkerSettings")):
            if st[key]:
                args.append(f"{label}: [" + ", ".join(st[key]) + "]")
        decls.append("        .target(name: " + ",\n                ".join(args) + ")")

    # The test target becomes an executable with a generated @main.
    test_src = source_dir(pkg, test)
    test_dst = os.path.join(out, "Sources", test_name)
    copy_target(test_src, test_dst, test.get("exclude", []))
    if os.path.exists(os.path.join(test_dst, "main.swift")):
        fail(f"{test_name}: has a main.swift, which conflicts with the generated entry point")
    with open(os.path.join(test_dst, ENTRY_FILE), "w") as f:
        f.write(ENTRY_SOURCE)
    st = settings_swift(test.get("settings", []), test_name)
    swift_flags = st["swift"] + [f'.unsafeFlags(["-F", {swift_str(FRAMEWORKS)}])']
    linker_flags = st["linker"] + [
        f'.unsafeFlags(["-F", {swift_str(FRAMEWORKS)}, "-framework", "Testing", "-Xlinker", "-rpath", "-Xlinker", {swift_str(FRAMEWORKS)}])'
    ]
    args = [swift_str(test_name), "dependencies: [" + ", ".join(swift_str(d) for d in dep_names(test)) + "]"]
    res = resources_swift(test.get("resources", []))
    if res:
        args.append("resources: [" + ", ".join(res) + "]")
    args.append("swiftSettings: [" + ", ".join(swift_flags) + "]")
    args.append("linkerSettings: [" + ", ".join(linker_flags) + "]")
    decls.append("        .executableTarget(name: " + ",\n                ".join(args) + ")")

    platforms = []
    for p in dump.get("platforms", []):
        name = {"macos": "macOS"}.get(p["platformName"])
        if name:
            v = p["version"].replace(".", "_")
            if v.endswith("_0"):
                v = v[:-2]
            platforms.append(f".{name}(.v{v})")
    manifest = (
        "// swift-tools-version:5.9\n"
        "// Generated by scripts/run-tests.sh from ../../Package.swift. Do not edit; it is rewritten on every run.\n"
        "import PackageDescription\n\n"
        "let package = Package(\n"
        f"    name: {swift_str(test_name + 'Runner')},\n"
        + (f"    platforms: [{', '.join(platforms)}],\n" if platforms else "")
        + "    targets: [\n" + ",\n".join(decls) + "\n    ]\n)\n"
    )
    with open(os.path.join(out, "Package.swift"), "w") as f:
        f.write(manifest)
    print(out)


if __name__ == "__main__":
    main()
