"""Turns a swift-testing test target into plain Swift for toolchains without the Testing module.

Used by make_runner_package.py --shim (see scripts/README.md). Swift 5.10 Command Line Tools ship no
swift-testing at all, so the normal runner cannot even compile the tests. This rewrites the few Testing
constructs the daemon's tests use into calls to a small shim (SHIM_SOURCE) and generates an @main that
runs every @Test function. Anything it does not understand makes it fail loudly rather than skip tests.
"""
import os
import re

SHIM_FILE = "__GhostkeysTestShim.swift"
ENTRY_FILE = "__GhostkeysTestRunnerMain.swift"

SHIM_SOURCE = """// Generated by scripts/run-tests.sh --shim. Minimal stand-ins for swift-testing's macros.
import Foundation

nonisolated(unsafe) var __gkIssues: [String] = []
struct __GkRequireFailed: Error {}

func __gkRecord(_ what: String, _ file: String, _ line: Int) { __gkIssues.append("\\(file):\\(line): \\(what)") }

func __gkExpect(_ c: @autoclosure () throws -> Bool, _ comment: @autoclosure () -> String = "",
                file: String = #fileID, line: Int = #line) {
    do { if try !c() { __gkRecord("expectation failed " + comment(), file, line) } }
    catch { __gkRecord("expectation threw \\(error) " + comment(), file, line) }
}
func __gkExpectAsync(_ c: @autoclosure () async throws -> Bool, _ comment: @autoclosure () -> String = "",
                     file: String = #fileID, line: Int = #line) async {
    do { if try await !c() { __gkRecord("expectation failed " + comment(), file, line) } }
    catch { __gkRecord("expectation threw \\(error) " + comment(), file, line) }
}
func __gkExpectThrows<E: Error>(_ type: E.Type, file: String = #fileID, line: Int = #line, _ body: () throws -> Void) {
    do { try body(); __gkRecord("expected \\(E.self) to be thrown", file, line) }
    catch { if !(error is E) { __gkRecord("threw \\(error), expected \\(E.self)", file, line) } }
}
func __gkExpectThrows<E: Error & Equatable>(_ expected: E, file: String = #fileID, line: Int = #line, _ body: () throws -> Void) {
    do { try body(); __gkRecord("expected \\(expected) to be thrown", file, line) }
    catch { if (error as? E) != expected { __gkRecord("threw \\(error), expected \\(expected)", file, line) } }
}
func __gkRequire<T>(_ v: T?, _ comment: @autoclosure () -> String = "", file: String = #fileID, line: Int = #line) throws -> T {
    guard let v else { __gkRecord("required value was nil " + comment(), file, line); throw __GkRequireFailed() }
    return v
}
func __gkRequire(_ c: Bool, _ comment: @autoclosure () -> String = "", file: String = #fileID, line: Int = #line) throws {
    if !c { __gkRecord("requirement failed " + comment(), file, line); throw __GkRequireFailed() }
}
func __gkRequireAsync<T>(_ v: @autoclosure () async throws -> T?, _ comment: @autoclosure () -> String = "",
                         file: String = #fileID, line: Int = #line) async throws -> T {
    guard let x = try await v() else { __gkRecord("required value was nil " + comment(), file, line); throw __GkRequireFailed() }
    return x
}
enum Issue {
    static func record(_ comment: String = "", file: String = #fileID, line: Int = #line) { __gkRecord("issue: " + comment, file, line) }
}

nonisolated(unsafe) var __gkPassed = 0, __gkSkipped = 0
nonisolated(unsafe) var __gkFailed: [String] = []
func __gkRun(_ name: String, _ body: () async throws -> Void) async {
    __gkIssues = []
    do { try await body() } catch { if !(error is __GkRequireFailed) { __gkIssues.append("threw \\(error)") } }
    if __gkIssues.isEmpty { __gkPassed += 1 }
    else { __gkFailed.append(name); print("✘ \\(name)"); for i in __gkIssues { print("    \\(i)") } }
}
func __gkFinish() -> Never {
    let total = __gkPassed + __gkFailed.count
    let skipped = __gkSkipped > 0 ? ", \\(__gkSkipped) skipped" : ""
    if __gkFailed.isEmpty { print("Test run with \\(total) tests passed (shim runner\\(skipped)).") }
    else { print("Test run with \\(total) tests: \\(__gkFailed.count) FAILED (shim runner\\(skipped)).") }
    exit(__gkFailed.isEmpty ? 0 : 1)
}
"""

REWRITES = [
    (re.compile(r"#expect\(\s*throws:\s*"), "__gkExpectThrows("),
    (re.compile(r"#expect\((\s*)await\b"), r"await __gkExpectAsync(\1await"),
    (re.compile(r"#require\((\s*)await\b"), r"await __gkRequireAsync(\1await"),
    (re.compile(r"#expect\("), "__gkExpect("),
    (re.compile(r"#require\("), "__gkRequire("),
]


def _balanced(s, i):
    """s[i] == '('; returns the index just past the matching ')'. Skips simple string literals."""
    depth, j, in_str = 0, i, False
    while j < len(s):
        ch = s[j]
        if in_str:
            if ch == "\\":
                j += 1
            elif ch == '"':
                in_str = False
        elif ch == '"':
            in_str = True
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return j + 1
        j += 1
    raise ValueError("unbalanced parentheses in @Test attribute")


def convert_file(text, path):
    """Returns (new text, [(suite, func, is_async, condition or None)])."""
    text = re.sub(r"^import Testing\s*$", "", text, flags=re.M)
    tests, out, i, suite = [], [], 0, None
    token = re.compile(r"@Suite\b(\s*\()?|@Test\b|#(?:expect|require)\(")
    while True:
        m = token.search(text, i)
        if not m:
            out.append(text[i:])
            break
        out.append(text[i:m.start()])
        tok = m.group(0)
        if tok.startswith("@Suite"):
            end = _balanced(text, m.end() - 1) if m.group(1) else m.end()
            sm = re.compile(r"\s*(?:final\s+)?(?:struct|class)\s+(\w+)").match(text, end)
            if not sm:
                raise ValueError(f"{path}: @Suite is not followed by a struct or class")
            suite = sm.group(1)
            i = end
            continue
        if tok == "@Test":
            j = m.end()
            cond = None
            rest = text[j:]
            if rest.startswith("("):
                end = _balanced(text, j)
                args = text[j + 1:end - 1].strip()
                cm = re.fullmatch(r"\.enabled\(if:\s*(.*)\)", args, flags=re.S)
                if cm:
                    cond = cm.group(1)
                elif args.startswith("\"") and "," not in args:
                    pass  # display name only
                else:
                    raise ValueError(f"{path}: unsupported @Test arguments: {args}")
                j = end
            fm = re.compile(r"\s*func\s+(\w+)\(\)\s*(async)?\s*(throws)?").match(text, j)
            if not fm:
                raise ValueError(f"{path}: @Test is not followed by a parameterless func")
            if suite is None:
                raise ValueError(f"{path}: @Test func {fm.group(1)} outside a struct")
            tests.append((suite, fm.group(1), bool(fm.group(2)), cond))
            i = j
            continue
        # #expect / #require: the first rewrite that matches wins (most specific first).
        for rx, repl in REWRITES:
            mm = rx.match(text, m.start())
            if mm:
                out.append(mm.expand(repl))
                i = mm.end()
                break
    return "".join(out), tests


def convert_target(dst):
    """Rewrites every .swift file in dst in place and writes the shim and the @main entry point."""
    all_tests = []
    for root, _, files in os.walk(dst):
        for name in sorted(files):
            if not name.endswith(".swift"):
                continue
            path = os.path.join(root, name)
            with open(path) as f:
                text, tests = convert_file(f.read(), path)
            with open(path, "w") as f:
                f.write(text)
            all_tests += tests
    if not all_tests:
        raise ValueError("no @Test functions found")
    with open(os.path.join(dst, SHIM_FILE), "w") as f:
        f.write(SHIM_SOURCE)
    lines = [
        "// Generated by scripts/run-tests.sh --shim. Runs every @Test function; an optional first argument",
        "// runs only the tests whose Suite.name contains it.",
        "import Foundation",
        "",
        "@main",
        "enum GhostkeysTestRunnerMain {",
        "    static func main() async {",
        "        let only = CommandLine.arguments.dropFirst().first",
    ]
    for suite, fn, is_async, cond in all_tests:
        name = f"{suite}.{fn}"
        call = f"try await {suite}().{fn}()" if is_async else f"try {suite}().{fn}()"
        run = f'await __gkRun("{name}") {{ {call} }}'
        guard = f'only == nil || "{name}".contains(only!)'
        if cond:
            lines.append(f"        if {guard} {{ if {cond} {{ {run} }} else {{ __gkSkipped += 1; print(\"- {name} (skipped: disabled)\") }} }}")
        else:
            lines.append(f"        if {guard} {{ {run} }}")
    lines += ["        __gkFinish()", "    }", "}", ""]
    with open(os.path.join(dst, ENTRY_FILE), "w") as f:
        f.write("\n".join(lines))
    return len(all_tests)
